startFadeIn=18:18
endFadeIn=20:00
rotate=true
startFadeOut=4:18
endFadeOut=6:00
source=./nebula.png
#If you're reading this and got this pack from anywhere other than Modrinth, please note that whatever website you got it from is a content thief.
#Just support me on Modrinth instead of supporting criminal and immoral behavior. It can be found at https://modrinth.com/resourcepack/lads-skybox